### ISSUE TITLE
Stuck on block 3620, mainnet and testnet

### ISSUE THREAD

**Issue by jpass022** [LYRA-Block-Lattice/LyraPcWallet#2]
![image](https://user-images.githubusercontent.com/5889788/115153298-c6df4380-a03a-11eb-9d14-92ed4b1ca1cf.png)
Windows x64...
Stuck on block 3620 for mainnet and testnet. 
Do I need to do something else?

**Comment by MorgothCreator** [comment]
At this moment in node API the block number status is not implemented yet.

That number is handwritten into the application at the compilation time, not to display 0.

When the node will have that status, will be implemented in the wallet.
