### ISSUE TITLE
Can't transfer funds from 1 wallet address L5ZjawG4SpoZ1vMNUMSL57FwzASqi4uh1zsi6sGguohoxeg4FimPNrS4Q1pY8UvuyXf24QzQSrpNVBGUDNjn5Byd88ZqFt

### ISSUE THREAD

**Issue by jpass022** [LYRA-Block-Lattice/LyraPcWallet#4]
**Describe the bug**
Can't transfer funds from 1 wallet address using Nebula or the QT

**To Reproduce**
1. Try to send from this address and nothing happens

**Expected behavior**
I expect the coin transfer to another address to happen

**Screenshots**
wallet address - L5ZjawG4SpoZ1vMNUMSL57FwzASqi4uh1zsi6sGguohoxeg4FimPNrS4Q1pY8UvuyXf24QzQSrpNVBGUDNjn5Byd88ZqFt
Balances: LYR:823947600000000

![image](https://user-images.githubusercontent.com/5889788/126224243-de117d71-0842-4639-98cc-05d27be95e17.png)

https://nebula.lyra.live/showblock/L5ZjawG4SpoZ1vMNUMSL57FwzASqi4uh1zsi6sGguohoxeg4FimPNrS4Q1pY8UvuyXf24QzQSrpNVBGUDNjn5Byd88ZqFt

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 10.0 and Ubuntu 20.04
 - Browser [e.g. chrome, safari]  Chrome and Firefox

**Additional context**

**Comment by MorgothCreator** [comment]
Not an PC wallet issue
